import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { AppSidebarProvider } from "@/providers/sidebar-provider";
import Navbar from "@/components/global/navbar";
import FormContextProvider from "@/context/form-context";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });

const satoshi = localFont({
  src: [
    {
      path: "./fonts/Satoshi-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi-Variable.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi-Light.ttf",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${satoshi.variable} antialiased font-satoshi`}>
        <AppSidebarProvider>
          <FormContextProvider>
            <main className="w-full">
              <Navbar />
              <div className="md:p-6 p-4">{children}</div>
            </main>
          </FormContextProvider>
        </AppSidebarProvider>
      </body>
    </html>
  );
}
