import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { AppSidebarProvider } from "@/providers/sidebar-provider";
import Navbar from "@/components/global/navbar";
import FormContextProvider from "@/context/form-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}>
        <AppSidebarProvider>
          <FormContextProvider>
            <main className="w-full">
              <Navbar />
              <div className="md:p-6 p-4">{children}</div>
            </main>
          </FormContextProvider>
        </AppSidebarProvider>
      </body>
    </html>
  );
}
